[package]
name = "tforth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse = "0.1.2"
tokenizer = "0.1.2"

